//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaBarrial2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeonato_Equipo
    {
        public int IdcampeonatoEquipo { get; set; }
        public Nullable<int> idcampeonato { get; set; }
        public Nullable<System.Guid> idequipo { get; set; }
        public Nullable<decimal> Inscripcion { get; set; }
        public Nullable<decimal> Garantia { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}
