//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaBarrial2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Jugador = new HashSet<Jugador>();
            this.Campeonato_Equipo = new HashSet<Campeonato_Equipo>();
        }
    
        public System.Guid equipoId { get; set; }
        public string nom_equipo { get; set; }
        public string colores { get; set; }
        public System.DateTime fundacion { get; set; }
        public string Escudo { get; set; }
        public string Serie { get; set; }
        public string Estado { get; set; }
        public Nullable<int> id_dirigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador> Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campeonato_Equipo> Campeonato_Equipo { get; set; }
        public virtual Dirigente Dirigente { get; set; }
    }
}
