//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaBarrial2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public System.Guid JugadorId { get; set; }
        public string cedula { get; set; }
        public string nom_jugador { get; set; }
        public string apelli_jugador { get; set; }
        public Nullable<int> CARNET { get; set; }
        public System.Guid EquipoId { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string fotografia { get; set; }
        public Nullable<System.DateTime> afiliacion { get; set; }
        public string estadocivil { get; set; }
        public string instruccion { get; set; }
        public string profesion { get; set; }
        public string provincia { get; set; }
        public string parroquia { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
